### ISSUE TITLE
What is "swapMessageId" method supposed to do?

### ISSUE THREAD

**Issue by rxmoein** [tinode/typescript-sdk#1]
Hello, @or-else 
Can you explain me what exactly does this method? I'm a bit confused
Thanks

**Comment by or-else** [comment]
Each message is expected to have a unique ID (`seqId`). Normally the ID is issued by the server, but if the message is not yet delivered to the server there is no server-issued ID. So, the message is first assigned a fake client-generated ID. Once the message is delivered, `swapMessageId` is called to replace the fake ID with a server-issued ID.

**Comment by rxmoein** [comment]
Thank you. There something more, What if this field for? `msg.noForwarding`

**Comment by or-else** [comment]
The `msg._noForwarding` Is used to avoid message duplication when retrying failed `publish()`.
