### ISSUE TITLE
Changing the API and removing duplicated methods

### ISSUE THREAD

**Issue by rxmoein** [tinode/typescript-sdk#2]
@or-else 
Hello, I was wondering if we can remove some duplicated methods on topic class which also are available on tinode class. I mean we should have only one way to do some certain things and the difference of usage between these duplicated methods are just one parameter.
I hope doing this will decrease possibility of confusion about using the typescript SDK.

**Comment by or-else** [comment]
Which methods are duplicated?

**Comment by rxmoein** [comment]
I don't mean exact duplication but for example there is a `createMessage` method in both `Tinode` and `Topic` class. I know that the one implemented on `Topic` creates a message for that specific topic but as it does not do much stuff and it's just a wrapper, user can just use the one that is in `Tinode` class. So I think removing it from `Topic` class can be helpful.

**Comment by or-else** [comment]
The idea behid having two ways to send messages is to allow for finer control over communication. The `Topic` interface caches data on the client. The `Tinode` interface does not cache. The SDK may be used by different types of clients: a UI client (like Tinode webapp) would primarily use `Topic`, an automata (e.g. a write-only data collector) may primarity use `Tinode`.
