### ISSUE TITLE
Installing for Angular

### ISSUE THREAD

**Issue by sasharp** [tinode/typescript-sdk#3]
How to install this for Angular?

After 

`npm i tinode-sdk`

there is error:

```
TS7016: Could not find a declaration file for module 'tinode-sdk'. '/node_modules/tinode-sdk/umd/tinode.prod.js' implicitly has an 'any' type.   
Try `npm install @types/tinode-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'tinode-sdk';`
```

**Comment by rxmoein** [comment]
Hello, this package is still under development.

**Comment by sasharp** [comment]
So far I see

`npm i tinode-sdk`

installs the JavaScript-version. For the TypeScript-version you have to run 

`npm i git://github.com/tinode/typescript-sdk.git`

and import modules with full path. That isn't right way to import packages, but I will try to use it.

**Comment by rxmoein** [comment]
This package is not completed won't work for now

**Comment by sasharp** [comment]
ok, I would warn about it in Readme.md. Then better is to create @types/tinode-sdk for JavaScript for now.
